[pytest]
pythonpath = .
markers =
    smoke: critical tests that check basic functionality
    regression: full regression test suite
    positive: tests with valid input data
    negative: tests with invalid input data